// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbqVhi0EVCt0iShrko-gx4hT4eJKlXnVo',
    appId: '1:246684481212:web:3c65e9df3c4ef4a5c282b9',
    messagingSenderId: '246684481212',
    projectId: 'shopping-app-flutter-8f35d',
    authDomain: 'shopping-app-flutter-8f35d.firebaseapp.com',
    storageBucket: 'shopping-app-flutter-8f35d.appspot.com',
    measurementId: 'G-HD0R8RX7JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB39fFokyJjoa93sBuSpHndwK7_ys_FtRA',
    appId: '1:246684481212:android:cb474e07010b870ac282b9',
    messagingSenderId: '246684481212',
    projectId: 'shopping-app-flutter-8f35d',
    storageBucket: 'shopping-app-flutter-8f35d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUTU5bnc4EB0bpyFPcfy-cHnp1znffHTE',
    appId: '1:246684481212:ios:0b321f7e14dcc9bbc282b9',
    messagingSenderId: '246684481212',
    projectId: 'shopping-app-flutter-8f35d',
    storageBucket: 'shopping-app-flutter-8f35d.appspot.com',
    iosClientId: '246684481212-be3lj4ave10e931vanobjfajbnli6cen.apps.googleusercontent.com',
    iosBundleId: 'com.example.internProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUTU5bnc4EB0bpyFPcfy-cHnp1znffHTE',
    appId: '1:246684481212:ios:0b321f7e14dcc9bbc282b9',
    messagingSenderId: '246684481212',
    projectId: 'shopping-app-flutter-8f35d',
    storageBucket: 'shopping-app-flutter-8f35d.appspot.com',
    iosClientId: '246684481212-be3lj4ave10e931vanobjfajbnli6cen.apps.googleusercontent.com',
    iosBundleId: 'com.example.internProject',
  );
}
